### ISSUE TITLE
Autoencoder_Utils module not found

### ISSUE THREAD

**Issue by Atmyre** [weissercn/LHCb_PID_Compression#1]
Hi

I was trying to run Train.ipynb and noticed that it required Autoencoder_Utils module that I couldn't manage to find in repo. Did I miss something?

Update: same question about FunctionScaler

**Comment by weissercn** [comment]
Hi, I have now included Autoencoder_Utils. Please install FunctionScaler (pip install FunctionScaler).

**Comment by Atmyre** [comment]
Thank you for a prompt response!
